wandb_config:
    project_name: "RATE_MemoryMaze"
    wwandb: True

data_config:
  gamma: 1.0
  normalize: True
  only_non_zero_rewards: True

training_config:
  learning_rate: 0.0003 # 1e-3
  lr_end_factor: 0.1
  beta_1: 0.9
  beta_2: 0.95
  weight_decay: 0.1
  batch_size: 128 # 128 
  warmup_steps: 80  # 50
  grad_norm_clip: 1.0 # 1.0
  epochs: 100 #250
  ckpt_epoch: 25
  use_erl_stop: True
  # inference during training
  online_inference: True
  # ! WARNING ! INPORTANT INFO
  # * IF YOU WANT TO TRAIN DT WITH context_length=90 (or if you want to train RATE with
  # * 3 segments and context 30), set context_length=30 and sections=3
  context_length: 60 # if RATE/GRATE: L = L, if DT: L = sections * L
  sections: 3        # if RATE/GRATE: S = S, if DT: S = 1


model_config:
  mode: "memory_maze"
  STATE_DIM: 3
  ACTION_DIM: 6
  n_token: 10000 # vocab_size
  n_layer: 6 # 3
  n_head: 8 # 1
  d_model: 128 # 128
  d_head: 128 # 128 # divider of d_model
  d_inner: 128 # 128 # > d_model
  dropout: 0.2 # 0.2
  dropatt: 0.05 # 0.05
  mem_len: 2
  ext_len: 1
  tie_weight: False
  num_mem_tokens: 15 # 5 d_head * nmt = diff params
  mem_at_end: True

online_inference_config:
  use_argmax: False
  episode_timeout: 1000
  desired_return: 8





